//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomv_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonent()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id_abon { get; set; }
        public string number { get; set; }
        public string fio { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address_reg { get; set; }
        public string address_live { get; set; }
        public string pasport { get; set; }
        public string code_otdel { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
        public string num_dogovor { get; set; }
        public Nullable<System.DateTime> date_dogovor { get; set; }
        public string dogovor_type { get; set; }
        public string reason_end { get; set; }
        public string ls { get; set; }
        public string servis { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string num_of_oborud { get; set; }
        public string name_role { get; set; }
        public string pass { get; set; }
    
        public virtual Oborud Oborud { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual DogovorType DogovorType { get; set; }
    }
}
