//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomv_1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NevaTelecom1Entities : DbContext
    {
        private static NevaTelecom1Entities _context;
        public NevaTelecom1Entities()
            : base("name=NevaTelecom1Entities")
        {
        }

        public static NevaTelecom1Entities GetContext()
        {
            if (_context == null)
                _context = new NevaTelecom1Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonents { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Oborud> Oboruds { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Servi> Servis { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TypeProblem> TypeProblems { get; set; }
        public virtual DbSet<TypeServi> TypeServis { get; set; }
        public virtual DbSet<VidServi> VidServis { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<DogovorType> DogovorTypes { get; set; }
    }
}
