//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomv_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public int id_abon { get; set; }
        public string num_order { get; set; }
        public System.DateTime data_create { get; set; }
        public string name_serv { get; set; }
        public string name_vid { get; set; }
        public string name_type { get; set; }
        public string name_status { get; set; }
        public string describe { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string problem_type { get; set; }
        public int id_manager { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Servi Servi { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeProblem TypeProblem { get; set; }
        public virtual TypeServi TypeServi { get; set; }
        public virtual VidServi VidServi { get; set; }
    }
}
