//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomv_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id_task { get; set; }
        public string name_role { get; set; }
        public string date { get; set; }
        public string task1 { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
